### ISSUE TITLE
Can't change max file size

### ISSUE THREAD

**Issue by rhijjawi** [blenderskool/blaze#116]
Hi there, I wasn't able to modify the max file size on Blaze through the docker-compose file, is there something else I needed to do?
```version: '3'
services:
  blaze-server:
    environment:
      - WS_HOST=0.0.0.0
      - SERVER_HOST=0.0.0.0
      - WS_SIZE_LIMIT=100000000 
      - TORRENT_SIZE_LIMIT=300000000000
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 3030:3030
  blaze-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 80:80
    depends_on:
      - blaze-server
    volumes:
      - ./nginx/compose-nginx.conf:/etc/nginx/nginx.conf```

**Comment by blenderskool** [comment]
Hi, the environment variables specified under `blaze-server` should be specified under `blaze-client` (frontend) service.

You can read more about which ones should be used where [here](https://github.com/blenderskool/blaze#build-process)

**Comment by rhijjawi** [comment]
```version: '3'
services:
  blaze-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 3030:3030
  blaze-client:
    environment: 
      - WS_HOST=0.0.0.0
      - SERVER_HOST=0.0.0.0
      - WS_SIZE_LIMIT=100000000 
      - TORRENT_SIZE_LIMIT=300000000000
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 80:80
    depends_on:
      - blaze-server
    volumes:
      - ./nginx/compose-nginx.conf:/etc/nginx/nginx.conf```

This is the new `docker-compose.yml` but no changes are made, it still gives me an error. `File size is limited to 667mb`
Just to make sure, I am doing this correctly, right?
1. Save file changes
2. Kill both docker containers
3. `docker-compose` up -d --build

Should I maybe be remove all env vars except for `TORRENT_SIZE_LIMIT`?

**Comment by blenderskool** [comment]
Actually, the `blaze-client` service takes all the environment variables as build args, as they cant be changed once the front-end is built and running.

Your docker-compose file should look something like this
```yaml
blaze-client:
  build:
    context: .
    dockerfile: ./client/Dockerfile
    args:
      TORRENT_SIZE_LIMIT: 300000000000
      WS_SIZE_LIMIT: 100000000
      SERVER_HOST: 0.0.0.0
      WS_HOST: 0.0.0.0
  ports:
    - 80:80
  depends_on:
    - blaze-server
  volumes:
    - ./nginx/compose-nginx.conf:/etc/nginx/nginx.conf
```
